// 外部テロップ部品バンドルが import map 経由で参照する react 再エクスポート。
// Vite が解決・重複排除するため、エディタ本体と同一の react インスタンスになる。
//
// 注意: react は CJS のため `export * from 'react'` では Vite が named export を
// 静的に列挙できず、ブラウザで「does not provide an export named 'useMemo'」等に
// なる（R-10 の react-dom と同根・フィクスチャ e2e で実証済み）。
// named import 文は Vite の CJS interop で正しく解決されるため、
// 公開 API を明示的に import → re-export する。
import React, {
  Children,
  Component,
  Fragment,
  Profiler,
  PureComponent,
  StrictMode,
  Suspense,
  act,
  cloneElement,
  createContext,
  createElement,
  createRef,
  forwardRef,
  isValidElement,
  lazy,
  memo,
  startTransition,
  useCallback,
  useContext,
  useDebugValue,
  useDeferredValue,
  useEffect,
  useId,
  useImperativeHandle,
  useInsertionEffect,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
  useTransition,
  version,
} from 'react';

export {
  Children,
  Component,
  Fragment,
  Profiler,
  PureComponent,
  StrictMode,
  Suspense,
  act,
  cloneElement,
  createContext,
  createElement,
  createRef,
  forwardRef,
  isValidElement,
  lazy,
  memo,
  startTransition,
  useCallback,
  useContext,
  useDebugValue,
  useDeferredValue,
  useEffect,
  useId,
  useImperativeHandle,
  useInsertionEffect,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
  useTransition,
  version,
};
export default React;
