import {afterEach,beforeEach,expect,it} from 'vitest';
import {mkdtempSync,mkdirSync,readFileSync,rmSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer,type Server} from 'node:http';import type {AddressInfo} from 'node:net';
import {SequenceStore} from './store';import {SequenceService} from './service';import {handleSequenceApi} from './api';import {HttpError} from '../http';
import {applySequenceCommand} from '../../core/sequence/commands';import type {SequenceDocument} from '../../core/sequence/model';
function fixture():SequenceDocument{return {schemaVersion:2,id:'case',name:'私有保存検査',revision:0,fps:{num:30,den:1},resolution:{width:320,height:180},sequenceEndFrame:120,background:'#000',assets:[],transcripts:[],transitions:[],ducking:{enabled:false,strength:'mid'},tracks:[{id:'v',kind:'visual',name:'図形',enabled:true}],clips:[{id:'shape',trackId:'v',name:'元の図形',startFrame:0,durationFrames:120,clock:{offset:{num:0,den:1},rate:{num:1,den:1},duration:{num:120,den:1}},content:{kind:'shape',data:{kind:'rect',x1:.2,y1:.2,x2:.8,y2:.8,color:'#fff',thickness:'medium',opacity:1}}}]};}
let root:string,project:string,server:Server|undefined;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),'harness-cut-archive-'));project=join(root,'case');mkdirSync(project);new SequenceStore(project).save({document:fixture(),executionId:'initial',expectedSavedRevision:null});});
afterEach(async()=>{if(server){server.closeAllConnections();await new Promise<void>((resolve,reject)=>server!.close(error=>error?reject(error):resolve()));server=undefined;}rmSync(root,{recursive:true,force:true});});
it('uses actual HTTP cut/save, a new service after reload, and partial restore with strict request rejection',async()=>{
 let sessions=new SequenceService();server=createServer((req,res)=>{void handleSequenceApi(req,res,new URL(req.url!,'http://localhost'),root,sessions).catch(e=>{res.statusCode=e instanceof HttpError?e.status:500;res.end(String(e));});});await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+(server.address() as AddressInfo).port;
 const post=async(path:string,body:unknown)=>fetch(url+'/api/sequence/'+path+'?id=case',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
 let state=await (await post('session',{})).json();let response=await post('command',{sessionId:state.sessionId,expectedRevision:state.document.revision,executionId:'cut',command:{type:'ripple-delete',startFrame:30,endFrame:60}});expect(response.status).toBe(200);state=await response.json();expect(state.document.cutArchive.entries).toHaveLength(1);
 response=await post('save',{sessionId:state.sessionId,expectedRevision:state.document.revision,expectedSavedRevision:state.savedRevision,executionId:'saved-cut'});expect(response.status).toBe(200);const rawBefore=readFileSync(join(project,'.harness/project.v2.json'));sessions=new SequenceService();state=await (await post('session',{})).json();expect(state.canUndo).toBe(false);const entryId=state.document.cutArchive.entries[0].id;
 response=await post('command',{sessionId:state.sessionId,expectedRevision:state.document.revision,executionId:'malformed',command:{type:'restore-cut',entryId,range:{startFrame:0,endFrame:10,typo:true}}});expect(response.status).toBe(400);expect(readFileSync(join(project,'.harness/project.v2.json'))).toEqual(rawBefore);
 response=await post('command',{sessionId:state.sessionId,expectedRevision:state.document.revision,executionId:'restore',command:{type:'restore-cut',entryId,range:{startFrame:5,endFrame:15}}});expect(response.status).toBe(200);state=await response.json();expect(state.document.sequenceEndFrame).toBe(100);expect(state.document.cutArchive.entries).toHaveLength(2);
 response=await post('save',{sessionId:state.sessionId,expectedRevision:state.document.revision,expectedSavedRevision:state.savedRevision,executionId:'saved-restored'});expect(response.status).toBe(200);expect(new SequenceStore(project).load()!.document.cutArchive!.entries.map(e=>e.durationFrames)).toEqual([5,15]);expect(readdirSync(join(project,'.harness'))).toEqual(['external-edits','project.v2.json']);
});
it('rejects corrupt/oversized archive before taking save ownership and preserves stored bytes',()=>{const store=new SequenceStore(project),original=readFileSync(store.file),cut=applySequenceCommand(fixture(),{type:'ripple-delete',startFrame:30,endFrame:60});for(const mutate of [(d:SequenceDocument)=>{d.cutArchive!.entries[0]!.clips[0]!.clock.duration.den=0;},(d:SequenceDocument)=>{d.cutArchive!.entries[0]!.clips[0]!.name='x'.repeat(8*1024*1024);}]){const invalid=structuredClone(cut);mutate(invalid);expect(()=>store.save({document:invalid,expectedSavedRevision:0,executionId:'bad'})).toThrow();expect(readFileSync(store.file)).toEqual(original);expect(readdirSync(join(project,'.harness'))).toEqual(['project.v2.json']);}});
